package POJOS;
// Generated 09-feb-2022 11:07:57 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Curso generated by hbm2java
 */
public class Curso implements java.io.Serializable {

    private int codigo;
    private String nombre;
    private String familia;
    private Set<Alumnos> alumnoses = new HashSet<Alumnos>(0);

    public Curso() {
    }

    public Curso(int codigo) {
        this.codigo = codigo;
    }

    public Curso(int codigo, String nombre, String familia, Set<Alumnos> alumnoses) {
        this.codigo = codigo;
        this.nombre = nombre;
        this.familia = familia;
        this.alumnoses = alumnoses;
    }

    public int getCodigo() {
        return this.codigo;
    }

    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }

    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getFamilia() {
        return this.familia;
    }

    public void setFamilia(String familia) {
        this.familia = familia;
    }

    public Set<Alumnos> getAlumnoses() {
        return this.alumnoses;
    }

    public void setAlumnoses(Set<Alumnos> alumnoses) {
        this.alumnoses = alumnoses;
    }

    @Override
    public String toString() {
        return "Curso: " + "Cod: " + codigo + ". Nombre: " + nombre + ". Familia: " + familia + '.';
    }
}
