package POJOS;
// Generated 08-feb-2022 13:20:55 by Hibernate Tools 4.3.1



/**
 * Alumnos generated by hbm2java
 */
public class Alumnos  implements java.io.Serializable {


     private int mat;
     private String nombre;
     private Integer curso;

    public Alumnos() {
    }

	
    public Alumnos(int mat) {
        this.mat = mat;
    }
    public Alumnos(int mat, String nombre, Integer curso) {
       this.mat = mat;
       this.nombre = nombre;
       this.curso = curso;
    }
   
    public int getMat() {
        return this.mat;
    }
    
    public void setMat(int mat) {
        this.mat = mat;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Integer getCurso() {
        return this.curso;
    }
    
    public void setCurso(Integer curso) {
        this.curso = curso;
    }

    @Override
    public String toString() {
        return "Alumnos{" + "mat=" + mat + ", nombre=" + nombre + ", curso=" + curso + '}';
    }




}


